const brands = [
	{
		name: "Aarn Packs",
		link: "https://www.aarnpacks.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "bags"],
		countries: ["new-zealand"],
	},
	{
		name: "Advanced Elements",
		link: "https://www.advancedelements.com/",
		scale: "cottage",
		categories: ["bags", "packrafting"],
		countries: ["usa"],
	},
	{
		name: "Alpacka Raft",
		link: "https://www.alpackaraft.com/",
		scale: "brand",
		categories: ["packrafting"],
		countries: ["usa"],
	},
	{
		name: "Alpine Luddites",
		link: "https://www.alpineluddites.com/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"knives",
			"bags",
			"snow",
			"bikepacking",
		],
		countries: ["usa"],
	},
	{
		name: "Alpkit",
		link: "https://www.alpkit.com/",
		scale: "brand",
		categories: [
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"bags",
			"food",
			"poles",
			"tech",
			"bikepacking",
		],
		countries: ["uk"],
	},
	{
		name: "Amok Equipment",
		link: "https://www.amokequipment.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep"],
		countries: ["norway", "usa"],
	},
	{
		name: "AnitGravityGear",
		link: "https://www.antigravitygear.com/",
		scale: "cottage",
		categories: [
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"clothing",
			"knives",
			"bags",
			"health",
			"water",
			"fire",
			"tech",
			"diy",
		],
		countries: ["usa"],
	},
	{
		name: "Appy Trails",
		link: "https://appytrails.com/",
		scale: "cottage",
		categories: ["tents"],
		countries: ["usa"],
	},
	{
		name: "Aquamira",
		link: "https://www.aquamira.com/",
		scale: "brand",
		categories: ["water"],
		countries: ["usa"],
	},
	{
		name: "Arrowhead Equipment",
		link: "https://www.arrowhead-equipment.com/",
		scale: "cottage",
		categories: [
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"clothing",
			"bags",
			"health",
			"water",
			"fire",
			"furniture",
			"tech",
			"diy",
		],
		countries: ["usa"],
	},
	{
		name: "As Tucas",
		link: "https://astucas.com/",
		scale: "cottage",
		categories: ["tents", "sleep", "clothing"],
		countries: ["spain"],
	},
	{
		name: "Atelier Blue Bottle",
		link: "https://www.atelierbluebottle.com/",
		scale: "cottage",
		categories: ["backpacks", "clothing", "bags"],
		countries: ["japan"],
	},
	{
		name: "Atom Packs",
		link: "https://atompacks.co.uk/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["uk"],
	},
	{
		name: "Balloonbed",
		link: "http://www.balloonbed.com/",
		scale: "cottage",
		categories: ["sleep"],
		countries: ["uk"],
	},
	{
		name: "Banks Fry-Bake Pans",
		link: "https://frybake.com/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Bare Boxer",
		link: "https://www.bareboxer.com/",
		scale: "cottage",
		categories: ["bags"],
		countries: ["usa"],
	},
	{
		name: "BatchStovez",
		link: "https://www.batchstovez.com/",
		scale: "cottage",
		categories: ["kitchen", "water"],
		countries: ["usa"],
	},
	{
		name: "Bear Bones Bivvy Gear",
		link: "https://www.bearbonesbikepacking.co.uk/",
		scale: "brand",
		categories: ["tents", "sleep", "kitchen", "bags", "bikepacking"],
		countries: ["uk"],
	},
	{
		name: "BearPaw Wilderness Designs",
		link: "https://www.bearpawwd.com/",
		scale: "cottage",
		categories: ["tents", "sleep", "bags", "poles", "diy", "bikepacking"],
		countries: ["usa"],
	},
	{
		name: "BearVault",
		link: "https://www.bearvault.com/",
		scale: "brand",
		categories: ["bags"],
		countries: ["usa"],
	},
	{
		name: "Beyond Clothing",
		link: "https://www.beyondclothing.com/",
		scale: "brand",
		categories: ["clothing", "knives"],
		countries: ["usa"],
	},
	{
		name: "Big Agnes",
		link: "https://bigagnes.com/",
		scale: "brand",
		categories: ["tents", "sleep", "clothing", "bags", "poles", "furniture"],
		countries: ["usa"],
	},
	{
		name: "Big Sky International",
		link: "https://bigskyinternational.com/",
		scale: "cottage",
		categories: ["tents", "sleep"],
		countries: ["usa"],
	},
	{
		name: "Bike Bag Dude",
		link: "https://www.bikebagdude.com/",
		scale: "cottage",
		categories: ["bikepacking"],
		countries: ["australia"],
	},
	{
		name: "Black Diamond",
		link: "https://www.blackdiamondequipment.com/",
		scale: "brand",
		categories: [
			"backpacks",
			"tents",
			"clothing",
			"health",
			"poles",
			"tech",
			"snow",
		],
		countries: ["usa", "international"],
	},
	{
		name: "Blizzard Survival",
		link: "https://www.blizzardsurvival.com/",
		scale: "brand",
		categories: ["sleep", "clothing", "health", "snow"],
		countries: ["uk", "usa"],
	},
	{
		name: "Blue Bolt Gear",
		link: "https://blueboltgear.com/",
		scale: "cottage",
		categories: ["sleep"],
		countries: ["usa"],
	},
	{
		name: "Borah Gear",
		link: "https://www.borahgear.com/",
		scale: "cottage",
		categories: ["tents", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Boreas",
		link: "https://www.boreasgear.com/",
		scale: "brand",
		categories: ["backpacks", "bags"],
		countries: ["usa"],
	},
	{
		name: "Brasslite",
		link: "https://brasslite.com/",
		scale: "cottage",
		categories: ["kitchen", "water"],
		countries: ["usa"],
	},
	{
		name: "Brynje of Norway",
		link: "https://www.brynje.no/",
		scale: "brand",
		categories: ["clothing"],
		countries: ["norway"],
	},
	{
		name: "Burgeon Outdoor",
		link: "https://www.burgeonoutdoor.com/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "Bushbuddy",
		link: "https://bushbuddystove.com/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Butt in a Sling",
		link: "https://www.buttinasling.com/",
		scale: "cottage",
		categories: ["hammocks", "diy"],
		countries: ["usa"],
	},
	{
		name: "Cave Creek Hammock",
		link: "https://www.cavecreekhammock.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep"],
		countries: ["usa"],
	},
	{
		name: "Chicken Tramper Ultralight Gear",
		link: "https://chickentrampergear.com/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["usa"],
	},
	{
		name: "CiloGear",
		link: "https://www.cilogear.com/",
		scale: "cottage",
		categories: ["backpacks", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Cioch Outdoor Clothing",
		link: "https://www.cioch-direct.co.uk/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["uk"],
	},
	{
		name: "Clark Outdoor",
		link: "https://www.junglehammock.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "clothing"],
		countries: ["usa"],
	},
	{
		name: "Clikstand",
		link: "https://www.clikstand.com/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Cnoc Outdoors",
		link: "https://cnocoutdoors.com/",
		scale: "cottage",
		categories: ["water"],
		countries: ["usa"],
	},
	{
		name: "Cooke Custom Sewing",
		link: "https://www.cookecustomsewing.com/",
		scale: "cottage",
		categories: ["tents", "bags", "furniture"],
		countries: ["usa"],
	},
	{
		name: "Crescent Moon",
		link: "https://www.crescentmoonsnowshoes.com/",
		scale: "brand",
		categories: ["snow"],
		countries: ["usa"],
	},
	{
		name: "Crux",
		link: "https://www.crux.uk.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "sleep", "clothing", "bags"],
		countries: ["uk"],
	},
	{
		name: "CUMULUS",
		link: "https://cumulus.equipment/",
		scale: "cottage",
		categories: ["sleep", "clothing", "hammocks"],
		countries: ["poland"],
	},
	{
		name: "Darn Tough",
		link: "https://darntough.com/",
		scale: "brand",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "DD Hammocks",
		link: "https://www.ddhammocks.com/",
		scale: "cottage",
		categories: [
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"clothing",
			"bags",
			"health",
			"water",
			"fire",
			"poles",
		],
		countries: ["uk"],
	},
	{
		name: "Dirty Girl Gaiters",
		link: "https://dirtygirlgaiters.com/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "Discovery Trekking Outfitters",
		link: "https://www.discoverytrekking.com/",
		scale: "cottage",
		categories: ["clothing", "diy"],
		countries: ["canada"],
	},
	{
		name: "DIY Gear Supply",
		link: "https://diygearsupply.com/",
		scale: "cottage",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "Down Works",
		link: "https://www.downworks.com/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"knives",
			"bags",
			"water",
			"fire",
			"furniture",
			"tech",
		],
		countries: ["usa"],
	},
	{
		name: "Dr. Bronner's",
		link: "https://www.drbronner.com/",
		scale: "brand",
		categories: ["health"],
		countries: ["usa"],
	},
	{
		name: "Dream Hammock",
		link: "https://www.dream-hammock.com/",
		scale: "cottage",
		categories: ["hammocks"],
		countries: ["usa"],
	},
	{
		name: "Duckworth",
		link: "https://www.duckworthco.com/",
		scale: "brand",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "DutchWare Gear",
		link: "https://dutchwaregear.com/",
		scale: "cottage",
		categories: [
			"tents",
			"hammocks",
			"kitchen",
			"clothing",
			"health",
			"water",
			"fire",
			"tech",
			"diy",
		],
		countries: ["usa"],
	},
	{
		name: "Eagles Nest Outfitters (ENO)",
		link: "https://www.eaglesnestoutfittersinc.com/",
		scale: "brand",
		categories: [
			"backpacks",
			"tents",
			"hammocks",
			"sleep",
			"bags",
			"furniture",
			"tech",
		],
		countries: ["usa"],
	},
	{
		name: "EmberLit",
		link: "https://emberlit.com/",
		scale: "cottage",
		categories: ["kitchen", "bags", "fire"],
		countries: ["usa"],
	},
	{
		name: "Enlightened Equipment",
		link: "https://www.enlightenedequipment.com/",
		scale: "cottage",
		categories: ["sleep", "clothing", "bags", "health"],
		countries: ["usa"],
	},
	{
		name: "Epiphany Outdoor Gear",
		link: "https://www.pocketbellows.com/",
		scale: "cottage",
		categories: ["fire"],
		countries: ["usa"],
	},
	{
		name: "Equinox",
		link: "https://www.equinoxltd.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "sleep", "clothing", "bags", "diy"],
		countries: ["usa"],
	},
	{
		name: "Etowah Outfitters",
		link: "http://www.etowahoutfittersultralightbackpackinggear.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "sleep", "kitchen", "bags"],
		countries: ["usa"],
	},
	{
		name: "Exotac Fire Starters",
		link: "https://www.exotac.com/",
		scale: "cottage",
		categories: ["fire"],
		countries: ["usa"],
	},
	{
		name: "Exped",
		link: "https://www.exped.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "hammocks", "sleep", "bags"],
		countries: ["switzerland", "international"],
	},
	{
		name: "Feathered Friends",
		link: "https://featheredfriends.com/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"health",
			"water",
			"tech",
		],
		countries: ["usa"],
	},
	{
		name: "Fibraplex",
		link: "https://fibraplex.com/",
		scale: "cottage",
		categories: ["tents"],
		countries: ["usa"],
	},
	{
		name: "Final Flame Gear",
		link: "https://finalflamegear.com/",
		scale: "cottage",
		categories: ["kitchen", "diy"],
		countries: ["japan"],
	},
	{
		name: "Firebox Stove",
		link: "https://fireboxstove.com/",
		scale: "cottage",
		categories: ["hammocks", "kitchen", "bags", "water", "fire", "furniture"],
		countries: ["usa"],
	},
	{
		name: "Flat Cat Gear",
		link: "https://www.flatcatgear.com/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Forty Below",
		link: "https://www.40below.com/",
		scale: "cottage",
		categories: ["clothing", "bags", "water"],
		countries: ["usa"],
	},
	{
		name: "Four Dog Stove Co.",
		link: "https://fourdog.com/",
		scale: "cottage",
		categories: ["kitchen", "fire"],
		countries: ["usa"],
	},
	{
		name: "Fozzils",
		link: "https://www.fozzils.com/",
		scale: "brand",
		categories: ["fire"],
		countries: ["usa"],
	},
	{
		name: "Freelight",
		link: "https://freelight.shop-pro.jp/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"bags",
			"poles",
		],
		countries: ["japan"],
	},
	{
		name: "Garage Grown Gear",
		link: "https://www.garagegrowngear.com/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"clothing",
			"knives",
			"bags",
			"water",
			"food",
			"tech",
			"snow",
			"packrafting",
		],
		countries: ["usa"],
	},
	{
		name: "GooseFeet Gear",
		link: "https://goosefeetgear.com/",
		scale: "cottage",
		categories: ["sleep", "clothing"],
		countries: ["usa"],
	},
	{
		name: "Gossamer Gear",
		link: "https://gossamergear.com/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"knives",
			"bags",
			"health",
			"water",
			"fire",
			"poles",
			"diy",
		],
		countries: ["usa"],
	},
	{
		name: "Grand Shelters",
		link: "https://www.grandshelters.com/",
		scale: "cottage",
		categories: ["tents"],
		countries: ["usa"],
	},
	{
		name: "Grand Trunk",
		link: "https://www.grandtrunk.com/",
		scale: "cottage",
		categories: ["hammocks"],
		countries: ["usa"],
	},
	{
		name: "Granite Gear",
		link: "https://www.granitegear.com/",
		scale: "brand",
		categories: ["backpacks", "kitchen", "bags", "water"],
		countries: ["usa"],
	},
	{
		name: "Grayl",
		link: "https://www.thegrayl.com/",
		scale: "brand",
		categories: ["water"],
		countries: ["usa"],
	},
	{
		name: "Greenbelly Meals",
		link: "https://www.greenbelly.co/",
		scale: "cottage",
		categories: ["food"],
		countries: ["usa"],
	},
	{
		name: "Gryphon Gear",
		link: "https://www.gryphongear.com/",
		scale: "cottage",
		categories: ["sleep"],
		countries: ["usa"],
	},
	{
		name: "Hammock Bliss",
		link: "https://www.hammockbliss.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep"],
		countries: ["australia", "international"],
	},
	{
		name: "Hammock Gear",
		link: "https://www.hammockgear.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep", "diy"],
		countries: ["usa"],
	},
	{
		name: "HammockTent",
		link: "https://www.hammocktent.com/",
		scale: "cottage",
		categories: ["tents", "hammocks"],
		countries: ["switzerland"],
	},
	{
		name: "HANCHOR",
		link: "https://www.hanchor.com/",
		scale: "cottage",
		categories: ["backpacks", "sleep", "clothing", "bags", "water"],
		countries: ["taiwan"],
	},
	{
		name: "Harmony House Foods",
		link: "https://www.harmonyhousefoods.com/",
		scale: "cottage",
		categories: ["food"],
		countries: ["usa"],
	},
	{
		name: "Hawbuck",
		link: "https://www.hawbuck.camp/",
		scale: "cottage",
		categories: ["bags"],
		countries: ["usa"],
	},
	{
		name: "HawK VittleS",
		link: "https://www.hawkvittles.com/",
		scale: "cottage",
		categories: ["food"],
		countries: ["usa"],
	},
	{
		name: "Helinox",
		link: "https://www.helinox.com.au/",
		scale: "brand",
		categories: ["tents", "poles", "furniture"],
		countries: ["australia"],
	},
	{
		name: "Hennessy Hammock",
		link: "https://hennessyhammock.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "hammocks", "kitchen", "clothing"],
		countries: ["canada", "usa"],
	},
	{
		name: "Hikelight",
		link: "https://hikelight.com/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"clothing",
			"knives",
			"bags",
			"health",
			"water",
			"food",
			"poles",
			"tech",
		],
		countries: ["usa"],
	},
	{
		name: "Hill People Gear",
		link: "https://www.hillpeoplegear.com/",
		scale: "cottage",
		categories: ["backpacks", "kitchen", "clothing", "bags", "health"],
		countries: ["usa"],
	},
	{
		name: "Hilleberg the Tentmaker",
		link: "https://hilleberg.com/",
		scale: "brand",
		categories: ["tents", "clothing", "water"],
		countries: ["sweden", "usa"],
	},
	{
		name: "Hillsound",
		link: "https://hillsound.com/",
		scale: "brand",
		categories: ["clothing", "snow"],
		countries: ["canada"],
	},
	{
		name: "Hilltop Packs",
		link: "https://hilltoppacks.com/",
		scale: "cottage",
		categories: ["backpacks", "kitchen", "bags"],
		countries: ["usa"],
	},
	{
		name: "Hofman Outdoor Gear Supply",
		link: "https://hofmanoutdoorgearsupply.ca/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep", "diy"],
		countries: ["canada"],
	},
	{
		name: "Hummingbird Hammocks",
		link: "https://hummingbirdhammocks.com/",
		scale: "cottage",
		categories: ["hammocks"],
		countries: ["usa"],
	},
	{
		name: "HydroBlu",
		link: "https://hydroblu.com/",
		scale: "brand",
		categories: ["water"],
		countries: ["usa"],
	},
	{
		name: "Hyperlite Mountain Gear",
		link: "https://www.hyperlitemountaingear.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "clothing", "bags", "water"],
		countries: ["usa"],
	},
	{
		name: "if you have",
		link: "https://ifyouhave.stores.jp/",
		scale: "cottage",
		categories: ["kitchen", "bags"],
		countries: ["japan"],
	},
	{
		name: "Jacks ‘R’ Better",
		link: "https://www.jacksrbetter.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep"],
		countries: ["usa"],
	},
	{
		name: "Jetboil",
		link: "https://www.jetboil.com/",
		scale: "brand",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Kahtoola",
		link: "https://kahtoola.com/",
		scale: "brand",
		categories: ["snow"],
		countries: ["usa"],
	},
	{
		name: "Kammok",
		link: "https://kammok.com/",
		scale: "brand",
		categories: ["tents", "hammocks", "sleep", "clothing"],
		countries: ["usa"],
	},
	{
		name: "Katabatic Gear",
		link: "https://katabaticgear.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "sleep", "bags", "water"],
		countries: ["usa"],
	},
	{
		name: "Katadyn",
		link: "https://www.katadyn.com/",
		scale: "brand",
		categories: ["water"],
		countries: ["usa"],
	},
	{
		name: "Kifaru",
		link: "https://kifaru.net/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"bags",
			"water",
			"snow",
		],
		countries: ["usa"],
	},
	{
		name: "Klymit",
		link: "https://www.klymit.com/",
		scale: "brand",
		categories: ["backpacks", "sleep"],
		countries: ["usa"],
	},
	{
		name: "KS Ultralight Gear",
		link: "https://www.ks-ultralightgear.com/",
		scale: "cottage",
		categories: ["backpacks", "bags", "water", "bikepacking"],
		countries: ["japan"],
	},
	{
		name: "Laufbursche",
		link: "https://www.laufbursche-gear.de/",
		scale: "cottage",
		categories: ["backpacks", "sleep", "kitchen", "knives"],
		countries: ["germany"],
	},
	{
		name: "Lawson Outdoor Equipment",
		link: "https://lawsonequipment.com/",
		scale: "cottage",
		categories: ["tents", "clothing"],
		countries: ["usa"],
	},
	{
		name: "Leatherman",
		link: "https://www.leatherman.com/",
		scale: "brand",
		categories: ["knives"],
		countries: ["usa"],
	},
	{
		name: "LifeStraw",
		link: "https://lifestraw.com/",
		scale: "brand",
		categories: ["water"],
		countries: ["switzerland", "international"],
	},
	{
		name: "Light My Fire",
		link: "https://www.lightmyfire.com/",
		scale: "brand",
		categories: ["kitchen", "knives", "bags", "water", "fire"],
		countries: ["sweden", "usa"],
	},
	{
		name: "LightHeart Gear",
		link: "https://www.lightheartgear.com/",
		scale: "cottage",
		categories: ["tents", "clothing", "bags", "water", "poles"],
		countries: ["usa"],
	},
	{
		name: "Lightwave",
		link: "https://www.lightwave.uk.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "sleep"],
		countries: ["uk"],
	},
	{
		name: "LiteAF",
		link: "https://liteaf.com/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["usa"],
	},
	{
		name: "Lite Outdoors",
		link: "https://www.liteoutdoors.com/",
		scale: "cottage",
		categories: ["tents", "kitchen", "diy"],
		countries: ["canada"],
	},
	{
		name: "Litesmith",
		link: "https://www.litesmith.com/",
		scale: "cottage",
		categories: ["hammocks", "kitchen", "knives", "health", "furniture"],
		countries: ["usa"],
	},
	{
		name: "Littlbug Enterprises",
		link: "https://littlbug.com/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Little Shop Of Hammocks",
		link: "https://www.littleshopofhammocks.com/",
		scale: "cottage",
		categories: ["hammocks", "sleep", "diy"],
		countries: ["canada"],
	},
	{
		name: "Loco Libre Gear",
		link: "https://www.locolibregear.com/",
		scale: "cottage",
		categories: ["sleep", "clothing"],
		countries: ["usa"],
	},
	{
		name: "Locus Gear",
		link: "https://locusgear.com/",
		scale: "cottage",
		categories: ["tents", "sleep", "clothing", "bags", "poles"],
		countries: ["japan"],
	},
	{
		name: "Loksak",
		link: "https://loksak.com/",
		scale: "brand",
		categories: ["bags"],
		countries: ["usa"],
	},
	{
		name: "LuminAID",
		link: "https://luminaid.com/",
		scale: "brand",
		categories: ["tech"],
		countries: ["usa"],
	},
	{
		name: "Luxe Outdoor",
		link: "http://www.luxeoutdoor.com/",
		scale: "cottage",
		categories: ["tents", "sleep"],
		countries: ["hong-kong"],
	},
	{
		name: "LuxuryLite",
		link: "http://www.luxurylite.com/",
		scale: "cottage",
		categories: ["backpacks", "sleep"],
		countries: ["usa"],
	},
	{
		name: "Marmot",
		link: "https://www.marmot.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "sleep", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Marupei",
		link: "https://marupei.net/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["japan"],
	},
	{
		name: "MaryJanesFarm",
		link: "https://shop.maryjanesfarm.org/",
		scale: "cottage",
		categories: ["kitchen", "food"],
		countries: ["usa"],
	},
	{
		name: "McHale Packs",
		link: "https://www.mchalepacks.com/",
		scale: "cottage",
		categories: ["backpacks"],
		countries: ["usa"],
	},
	{
		name: "MEC (Mountain Equipment Co-op)",
		link: "https://www.mec.ca/",
		scale: "brand",
		categories: [
			"backpacks",
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"clothing",
			"knives",
			"bags",
			"health",
			"water",
			"food",
			"fire",
			"poles",
			"furniture",
			"tech",
			"snow",
		],
		countries: ["canada"],
	},
	{
		name: "Melanzana",
		link: "https://melanzana.com/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "Monoral",
		link: "https://www.monoral.jp/",
		scale: "cottage",
		categories: ["furniture"],
		countries: ["japan"],
	},
	{
		name: "Montbell",
		link: "https://www.montbell.us/",
		scale: "brand",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"bags",
			"poles",
			"tech",
		],
		countries: ["usa"],
	},
	{
		name: "Moonbowgear",
		link: "https://moonbowgear.com/",
		scale: "cottage",
		categories: ["tents", "sleep", "kitchen", "bags", "water"],
		countries: ["usa"],
	},
	{
		name: "Mountain Hardwear",
		link: "https://www.mountainhardwear.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "sleep", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Mountain Laurel Designs",
		link: "https://mountainlaureldesigns.com/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"bags",
			"water",
			"diy",
		],
		countries: ["usa"],
	},
	{
		name: "MSR",
		link: "https://www.msrgear.com/",
		scale: "brand",
		categories: ["kitchen", "clothing", "water", "fire", "poles", "snow"],
		countries: ["usa"],
	},
	{
		name: "Mystery Ranch Backpacks",
		link: "https://www.mysteryranch.com/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["usa"],
	},
	{
		name: "Nashville Pack",
		link: "https://nashvillepack.com/",
		scale: "cottage",
		categories: ["backpacks"],
		countries: ["usa"],
	},
	{
		name: "Nemo Equipment",
		link: "https://www.nemoequipment.com/",
		scale: "brand",
		categories: ["tents", "sleep", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Next Mile Meals",
		link: "https://www.nextmilemeals.com/",
		scale: "cottage",
		categories: ["food"],
		countries: ["usa"],
	},
	{
		name: "Northern Lites",
		link: "https://northernlites.com/",
		scale: "brand",
		categories: ["snow"],
		countries: ["usa"],
	},
	{
		name: "Northern Ultralight",
		link: "https://www.northernultralight.com/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["canada"],
	},
	{
		name: "Nunatak Gear",
		link: "https://nunatakusa.com/",
		scale: "cottage",
		categories: ["sleep", "clothing"],
		countries: ["usa"],
	},
	{
		name: "NW Alpine",
		link: "https://nwalpine.com/",
		scale: "brand",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "OGAWAND",
		link: "https://ogawand.com/",
		scale: "cottage",
		categories: ["backpacks", "kitchen", "bags"],
		countries: ["japan"],
	},
	{
		name: "Olympic UltraLite",
		link: "https://www.olympicul.com/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["usa"],
	},
	{
		name: "OMM",
		link: "https://www.theomm.com/",
		scale: "brand",
		categories: ["backpacks", "sleep", "clothing", "bags", "water"],
		countries: ["uk"],
	},
	{
		name: "OookWorks",
		link: "https://oookworks.com/",
		scale: "cottage",
		categories: ["tents", "bags"],
		countries: ["uk"],
	},
	{
		name: "Osprey",
		link: "https://www.osprey.com/",
		scale: "brand",
		categories: ["backpacks", "water", "bikepacking"],
		countries: ["usa", "international"],
	},
	{
		name: "Outdoor Equipment Supplier",
		link: "https://outdoorequipmentsupplier.com/",
		scale: "cottage",
		categories: ["tents", "bags"],
		countries: ["usa"],
	},
	{
		name: "Outdoor Herbivore",
		link: "https://outdoorherbivore.com/",
		scale: "cottage",
		categories: ["food"],
		countries: ["usa"],
	},
	{
		name: "Outdoor Research",
		link: "https://www.outdoorresearch.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Outdoor Wilderness Fabrics",
		link: "https://www.owfinc.com/",
		scale: "cottage",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "Oware",
		link: "https://bivysack.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "sleep", "clothing", "bags", "diy"],
		countries: ["usa"],
	},
	{
		name: "Pa'lante Packs",
		link: "https://www.palantepacks.com/",
		scale: "cottage",
		categories: ["backpacks", "clothing"],
		countries: ["usa"],
	},
	{
		name: "PaagoWorks",
		link: "https://www.paagoworks.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "bags"],
		countries: ["japan"],
	},
	{
		name: "Pacerpole",
		link: "https://www.pacerpole.com/",
		scale: "cottage",
		categories: ["poles"],
		countries: ["uk"],
	},
	{
		name: "Packit Gourmet",
		link: "https://www.packitgourmet.com/",
		scale: "cottage",
		categories: ["kitchen", "knives", "food"],
		countries: ["usa"],
	},
	{
		name: "Packrafting Store",
		link: "https://www.packrafting-store.de/",
		scale: "cottage",
		categories: [
			"backpacks",
			"knives",
			"bags",
			"health",
			"water",
			"packrafting",
		],
		countries: ["germany"],
	},
	{
		name: "PAK-IT-LITE",
		link: "https://camphammocks.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "hammocks", "sleep"],
		countries: ["usa"],
	},
	{
		name: "Paleo Meals To Go",
		link: "https://paleomealstogo.com/",
		scale: "cottage",
		categories: ["water", "food"],
		countries: ["usa"],
	},
	{
		name: "Páramo",
		link: "https://www.paramo-clothing.com/",
		scale: "brand",
		categories: ["clothing"],
		countries: ["uk"],
	},
	{
		name: "Patagonia",
		link: "https://www.patagonia.com/",
		scale: "brand",
		categories: ["backpacks", "sleep", "kitchen", "clothing", "bags", "water"],
		countries: ["usa"],
	},
	{
		name: "Peter Limmer and Sons",
		link: "https://limmerboots.com/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "Petzl",
		link: "https://www.petzl.com/",
		scale: "brand",
		categories: ["backpacks", "clothing", "knives", "bags", "health", "tech"],
		countries: ["france", "usa"],
	},
	{
		name: "PHD",
		link: "https://phdesigns.co.uk/",
		scale: "cottage",
		categories: ["sleep", "clothing"],
		countries: ["uk"],
	},
	{
		name: "Photon Light",
		link: "https://www.photonlight.com/",
		scale: "brand",
		categories: ["knives", "tech"],
		countries: ["usa"],
	},
	{
		name: "PicharPak",
		link: "https://picharpak.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "kitchen", "bags"],
		countries: ["hong-kong"],
	},
	{
		name: "Powerenz",
		link: "https://www.powerenz.com/",
		scale: "cottage",
		categories: ["tech"],
		countries: ["usa"],
	},
	{
		name: "Purcell Trench",
		link: "https://www.purcelltrench.com/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Purple Rain Adventure Skirts",
		link: "https://www.purplerainskirts.com/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "QiWiz UL Gear",
		link: "http://www.qiwiz.net/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Quest Outfitters",
		link: "https://www.questoutfitters.com/",
		scale: "brand",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "R & R Enterprises",
		link: "https://www.backpackinglight.co.uk/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"clothing",
			"health",
			"water",
			"poles",
			"furniture",
			"tech",
			"diy",
		],
		countries: ["uk"],
	},
	{
		name: "Rab",
		link: "https://rab.equipment/",
		scale: "brand",
		categories: ["clothing"],
		countries: ["uk"],
	},
	{
		name: "Ragged Mountain",
		link: "https://raggedmountain.com/",
		scale: "cottage",
		categories: ["backpacks", "clothing", "bags", "water"],
		countries: ["usa"],
	},
	{
		name: "RaidLight",
		link: "https://raidlight.com/",
		scale: "brand",
		categories: ["backpacks", "clothing", "bags", "water", "poles"],
		countries: ["france", "international"],
	},
	{
		name: "Ray-Way Products (Ray Jardine)",
		link: "https://www.rayjardine.com/",
		scale: "cottage",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "RBH Designs",
		link: "https://www.rbhdesigns.com/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "Red Paw Packs",
		link: "https://redpawpacks.com/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["usa"],
	},
	{
		name: "RibzWear",
		link: "https://www.ribzwear.com/",
		scale: "cottage",
		categories: ["backpacks"],
		countries: ["usa"],
	},
	{
		name: "Ripstop by the Roll",
		link: "https://ripstopbytheroll.com/",
		scale: "cottage",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "Rivendell Mountain Works",
		link: "https://www.rivendellmountainworks.com/",
		scale: "cottage",
		categories: ["backpacks", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "RiverSideRambler",
		link: "https://www.riversiderambler.com/",
		scale: "cottage",
		categories: ["backpacks", "kitchen"],
		countries: ["japan"],
	},
	{
		name: "Rockywoods Fabrics",
		link: "https://www.rockywoods.com/",
		scale: "cottage",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "Ruta Locura",
		link: "https://www.rutalocura.com/",
		scale: "cottage",
		categories: ["tents", "kitchen", "clothing", "poles", "tech"],
		countries: ["usa"],
	},
	{
		name: "Sawyer",
		link: "https://sawyer.com/",
		scale: "brand",
		categories: ["health", "water"],
		countries: ["usa"],
	},
	{
		name: "Sea to Summit",
		link: "https://www.seatosummitusa.com/",
		scale: "brand",
		categories: [
			"backpacks",
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"clothing",
			"knives",
			"bags",
			"health",
			"water",
		],
		countries: ["australia", "usa"],
	},
	{
		name: "Seattle Fabrics",
		link: "https://www.seattlefabrics.com/",
		scale: "cottage",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "Seek Outside ",
		link: "https://seekoutside.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "kitchen"],
		countries: ["usa"],
	},
	{
		name: "Shelby",
		link: "https://www.shelby.fi/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"clothing",
			"bags",
			"water",
			"food",
			"tech",
			"diy",
			"snow",
		],
		countries: ["finland"],
	},
	{
		name: "Shelt",
		link: "https://shelt.official.ec/",
		scale: "cottage",
		categories: ["tents"],
		countries: ["japan"],
	},
	{
		name: "Sheltowee Hammock Company",
		link: "https://shellhammocks.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Sierra Madre Research",
		link: "https://www.sierramadreresearch.com/",
		scale: "cottage",
		categories: ["tents", "hammocks"],
		countries: ["usa"],
	},
	{
		name: "Simblissity",
		link: "https://www.simblissity.net/",
		scale: "cottage",
		categories: ["tents", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Simond",
		link: "https://www.simond.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "sleep", "clothing", "bags", "health"],
		countries: ["france"],
	},
	{
		name: "Simple Outdoor Solutions",
		link: "https://www.simpleoutdoorstore.com/",
		scale: "cottage",
		categories: ["sleep", "kitchen", "clothing", "bags", "water"],
		countries: ["usa"],
	},
	{
		name: "Simply Light Designs",
		link: "https://www.simplylightdesigns.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep", "bags", "diy"],
		countries: ["usa"],
	},
	{
		name: "Six Moon Designs",
		link: "https://www.sixmoondesigns.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "bags"],
		countries: ["usa"],
	},
	{
		name: "Smartwool",
		link: "https://www.smartwool.com/",
		scale: "brand",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "Snow Peak",
		link: "https://snowpeak.com/",
		scale: "brand",
		categories: [
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"knives",
			"bags",
			"water",
			"furniture",
			"tech",
		],
		countries: ["usa"],
	},
	{
		name: "Snugpak",
		link: "https://www.snugpak.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "sleep", "clothing", "bags", "water"],
		countries: ["uk"],
	},
	{
		name: "Solo Stove",
		link: "https://www.solostove.com/",
		scale: "cottage",
		categories: ["kitchen", "fire"],
		countries: ["usa"],
	},
	{
		name: "SOTO",
		link: "https://sotooutdoors.com/",
		scale: "brand",
		categories: ["kitchen"],
		countries: ["japan", "international"],
	},
	{
		name: "Speedster Backpacking Products",
		link: "https://speedsterstoves.co.uk/",
		scale: "cottage",
		categories: ["kitchen", "water", "fire"],
		countries: ["uk"],
	},
	{
		name: "Stephenson's Warmlite",
		link: "https://warmlite.com/",
		scale: "cottage",
		categories: ["tents", "sleep", "clothing"],
		countries: ["usa"],
	},
	{
		name: "Stormin Stove Systems",
		link: "https://www.storminstovesystems.co.uk/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["uk"],
	},
	{
		name: "Suluk 46",
		link: "https://www.suluk46.com/",
		scale: "cottage",
		categories: ["kitchen", "clothing", "furniture", "snow"],
		countries: ["canada"],
	},
	{
		name: "Supai Adventure Gear",
		link: "https://www.supaiadventuregear.com/",
		scale: "cottage",
		categories: ["packrafting"],
		countries: ["usa"],
	},
	{
		name: "Superior Wilderness Designs",
		link: "https://www.swdbackpacks.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "bags"],
		countries: ["usa"],
	},
	{
		name: "Tarptent",
		link: "https://www.tarptent.com/",
		scale: "cottage",
		categories: ["tents"],
		countries: ["usa"],
	},
	{
		name: "TentPole Technologies",
		link: "https://tentpoletechnologies.com/",
		scale: "cottage",
		categories: ["tents"],
		countries: ["usa"],
	},
	{
		name: "Terra Nova Equipment",
		link: "https://www.terra-nova.co.uk/",
		scale: "cottage",
		categories: [
			"backpacks",
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"bags",
			"water",
			"poles",
		],
		countries: ["uk"],
	},
	{
		name: "Terra Rosa Gear",
		link: "https://terrarosagear.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "hammocks", "sleep", "bags"],
		countries: ["australia"],
	},
	{
		name: "The North Face",
		link: "https://www.thenorthface.com/",
		scale: "brand",
		categories: ["backpacks", "tents", "clothing", "bags"],
		countries: ["usa", "international"],
	},
	{
		name: "The Packa",
		link: "https://www.thepacka.com/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "The Rain Shed",
		link: "https://www.therainshed.com/",
		scale: "cottage",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "Therm-a-Rest",
		link: "https://www.thermarest.com/",
		scale: "brand",
		categories: ["tents", "hammocks", "sleep", "furniture"],
		countries: ["usa"],
	},
	{
		name: "Thru-Hiker",
		link: "https://www.thru-hiker.com/",
		scale: "cottage",
		categories: ["diy"],
		countries: ["usa"],
	},
	{
		name: "Thrupack",
		link: "https://www.thrupack.com/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["usa"],
	},
	{
		name: "Tier Gear",
		link: "https://www.tiergear.com.au/",
		scale: "cottage",
		categories: [
			"tents",
			"hammocks",
			"sleep",
			"kitchen",
			"bags",
			"health",
			"diy",
		],
		countries: ["australia"],
	},
	{
		name: "Titanium Goat",
		link: "https://www.titaniumgoat.com/",
		scale: "cottage",
		categories: ["tents", "kitchen", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Toaks Outdoor",
		link: "https://www.toaksoutdoor.com/",
		scale: "brand",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Trail Designs",
		link: "https://www.traildesigns.com/",
		scale: "cottage",
		categories: ["kitchen", "knives", "water", "fire"],
		countries: ["usa"],
	},
	{
		name: "Trek Light Gear",
		link: "https://www.treklightgear.com/",
		scale: "cottage",
		categories: ["backpacks", "hammocks", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Trekkertent",
		link: "https://www.trekkertent.com/",
		scale: "cottage",
		categories: ["tents"],
		countries: ["uk"],
	},
	{
		name: "Triple Aught Design",
		link: "https://tripleaughtdesign.com/",
		scale: "brand",
		categories: ["backpacks", "clothing", "knives", "bags", "water", "tech"],
		countries: ["usa"],
	},
	{
		name: "UK Hammocks",
		link: "https://www.ukhammocks.co.uk/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep", "bags"],
		countries: ["uk"],
	},
	{
		name: "ULA Equipment",
		link: "https://www.ula-equipment.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "sleep", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Ultralight Hiker",
		link: "https://ultralighthiker.com.au/",
		scale: "cottage",
		categories: ["tents", "kitchen", "bags", "water", "food", "furniture"],
		countries: ["australia"],
	},
	{
		name: "Ultralight Outdoor Gear",
		link: "https://www.ultralightoutdoorgear.co.uk/",
		scale: "brand",
		categories: [
			"tents",
			"sleep",
			"kitchen",
			"clothing",
			"knives",
			"bags",
			"health",
			"water",
			"food",
			"fire",
			"poles",
			"tech",
			"snow",
			"bikepacking",
		],
		countries: ["uk"],
	},
	{
		name: "UGQ Outdoor",
		link: "https://ugqoutdoor.com/",
		scale: "cottage",
		categories: ["tents", "sleep", "bags"],
		countries: ["usa"],
	},
	{
		name: "Ursack",
		link: "https://www.ursack.com/",
		scale: "brand",
		categories: ["bags", "water", "tech"],
		countries: ["usa"],
	},
	{
		name: "Valandre",
		link: "https://www.valandre.com/",
		scale: "brand",
		categories: ["sleep", "clothing"],
		countries: ["france", "international"],
	},
	{
		name: "Vargo",
		link: "https://www.vargooutdoors.com/",
		scale: "brand",
		categories: [
			"backpacks",
			"tents",
			"kitchen",
			"clothing",
			"knives",
			"water",
			"fire",
			"snow",
		],
		countries: ["usa"],
	},
	{
		name: "Wanderlust Equipment",
		link: "https://wanderlust-equipment.com/",
		scale: "cottage",
		categories: ["tents", "kitchen", "bags"],
		countries: ["japan"],
	},
	{
		name: "Warbonnet Outdoors",
		link: "https://www.warbonnetoutdoors.com/",
		scale: "cottage",
		categories: ["tents", "hammocks", "sleep", "clothing", "bags"],
		countries: ["usa"],
	},
	{
		name: "Well Done",
		link: "https://welldone-nagoya.stores.jp/",
		scale: "cottage",
		categories: ["backpacks", "clothing"],
		countries: ["japan"],
	},
	{
		name: "Western Mountaineering",
		link: "https://www.westernmountaineering.com/",
		scale: "cottage",
		categories: ["sleep", "clothing"],
		countries: ["usa"],
	},
	{
		name: "White Box Stoves",
		link: "https://whiteboxalcoholstoves.com/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "Wiggy's",
		link: "https://www.wiggys.com/",
		scale: "brand",
		categories: ["tents", "sleep", "clothing"],
		countries: ["usa"],
	},
	{
		name: "Wild Ideas",
		link: "https://www.wild-ideas.net/",
		scale: "cottage",
		categories: ["bags"],
		countries: ["usa"],
	},
	{
		name: "Wild Things",
		link: "https://www.wildthingsgear.com/",
		scale: "brand",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "Wilderness Threadworks",
		link: "https://www.wildernessthreadworks.com/",
		scale: "cottage",
		categories: ["backpacks", "bikepacking"],
		countries: ["australia"],
	},
	{
		name: "Wintergreen Northern Wear",
		link: "https://www.wintergreennorthernwear.com/",
		scale: "cottage",
		categories: ["clothing"],
		countries: ["usa"],
	},
	{
		name: "YAMA Mountain Gear",
		link: "https://www.yamamountaingear.com/",
		scale: "cottage",
		categories: ["tents", "diy"],
		countries: ["usa"],
	},
	{
		name: "Yamatomichi",
		link: "https://yamatomichi.com/",
		scale: "cottage",
		categories: ["backpacks", "sleep", "clothing", "bags"],
		countries: ["japan"],
	},
	{
		name: "ZebraLight",
		link: "https://www.zebralight.com/",
		scale: "brand",
		categories: ["tech"],
		countries: ["usa"],
	},
	{
		name: "Zen Backpacking Stoves",
		link: "https://zenstoves.net/",
		scale: "cottage",
		categories: ["kitchen"],
		countries: ["usa"],
	},
	{
		name: "ZimmerBuilt",
		link: "https://www.zimmerbuilt.com/",
		scale: "cottage",
		categories: ["backpacks", "bags"],
		countries: ["usa"],
	},
	{
		name: "Zpacks",
		link: "https://zpacks.com/",
		scale: "cottage",
		categories: ["backpacks", "tents", "sleep", "kitchen", "clothing", "bags"],
		countries: ["usa"],
	},
] satisfies Brand[];

export interface Brand {
	name: string;
	link: string;
	scale: "cottage" | "brand";
	categories: (
		| "backpacks"
		| "tents"
		| "sleep"
		| "kitchen"
		| "clothing"
		| "tech"
		| "bags"
		| "diy"
		| "bikepacking"
		| "hammocks"
		| "knives"
		| "water"
		| "fire"
		| "snow"
		| "health"
		| "food"
		| "poles"
		| "packrafting"
		| "furniture"
	)[];
	countries: (
		| "international"
		| "usa"
		| "uk"
		| "australia"
		| "france"
		| "canada"
		| "finland"
		| "hong-kong"
		| "japan"
		| "germany"
		| "korea"
		| "sweden"
		| "taiwan"
		| "switzerland"
		| "poland"
		| "norway"
		| "spain"
		| "new-zealand"
	)[];
}

export default brands;
