name: Code Quality checks
on:
    pull_request:
        branches: [main]
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    prettier:
        name: Prettier
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: 'package.json'
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install -D -w
            - name: Check formatting with Prettier
              run: pnpm format:check
